spring:
  application:
    name: Cunion
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cunion
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session ????????
#  session:
#    timeout: 86400
#    store-type: redis
  # redis ??
  redis:
    port: 6379
    host: localhost
    database: 6
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
cunion:
  jwt:
    expire: 7
    cache-expire: 7
    secret: miJia
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)
oss:
  accessKey: 0-g7dHkM8qj24G2HrcPTo0EPpjcR_v1dj0q8bucB
  secretKey: L-BAqAxYUvrUPjhOkgwWb__RHSmKN7J0R8IpBGeV
  bucket: cunion